# Практическое задание NumPy

# Задание 1

In [2]:
#Импортируйте библиотеку Numpy и дайте ей псевдоним np.
import numpy as np

In [3]:
#Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел от 12 до 24 невключительно
np.arange(12,24)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
#Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
print(a.reshape(2,6))
print(a.reshape(3,4))
print(a.reshape(4,3))
print(a.reshape(6,2))
print(a.reshape(12,1))

NameError: name 'a' is not defined

In [5]:
'''Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Ответ: нет, массив двумерный, так как обращение к его элементам будет происходить с помощью двух индексов'''
print(a.reshape(-1,6))
print(a.reshape(-1,4))
print(a.reshape(-1,3))
print(a.reshape(6,-1))
print(a.reshape(12,-1))

NameError: name 'a' is not defined

In [6]:
'''Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из 
нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.'''
b = np.random.randn(3,4)
b

array([[-0.38525321,  1.71886112, -0.14016785, -0.17948075],
       [-1.75129227,  0.9666234 , -1.21851877,  0.07015354],
       [-0.13752295,  0.50944713, -0.79775437,  0.26278067]])

In [7]:
#Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
b = b.flatten()
b

array([-0.38525321,  1.71886112, -0.14016785, -0.17948075, -1.75129227,
        0.9666234 , -1.21851877,  0.07015354, -0.13752295,  0.50944713,
       -0.79775437,  0.26278067])

In [8]:
#Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2. 
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [9]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
b = np.arange(20, 0, -2).reshape(1, 10)
b
#В чем разница между массивами a и b?
#Ответ: Массив a - одномерный массив. Доступ к элементам осуществляется по одному индексу, а
#b - двумерный массив - доступ к элементам осуществляется с помощью двух индексов

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [10]:
#Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
#чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a = np.zeros((2,2))
a
b = np.ones((3,2))
b
v = np.vstack((a, b))
print(v)
v.size

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [11]:
#Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
#Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
#Получить матрицу At путем транспонирования матрицы A.
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [14]:
#Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [15]:
#Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
# Ответ: матрица B имеет размер 4х4. Обратная матрица не существует, т.к. ее определитель равен 0
#Bi = np.linalg.inv(B)
np.linalg.det(B)

0.0

In [16]:
#Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
np.random.seed(42)
#Создайте одномерный массив c, составленный из последовательности 16-ти 
#случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [17]:
#Поменяйте его форму так, чтобы получилась квадратная матрица C. 
C = c.reshape(4, -1)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [18]:
#Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
D = B + C*10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [19]:
#Вычислите определитель, ранг и обратную матрицу D_inv для D.
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
D_inv

-28511999.999999944
4


array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [20]:
#Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - 
#к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [21]:
'''С помощью функции numpy.where, используя матрицу D_inv в качестве маски, 
а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, 
для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны 
соответствующему элементу матрицы C.'''

print(B)
print(C)
np.where(D_inv, B, C)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

# Задание 2

In [22]:
'''Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.'''
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
print(a)
mean_a = a.mean(axis=0)
mean_a

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


array([2. , 8.4])

# Задание 3

In [23]:
'''Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив 
должен иметь размер 5x2.
'''
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 4

In [24]:
'''Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.
'''

a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp / (a_centered.shape[0] - 1)


2.0

# Задание 5

In [25]:
'''Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся 
в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, 
поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет 
равно элементу в строке с индексом 0 и столбце с индексом 1.
'''
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

# Практическое задание Pandas

# Задание 1

In [83]:
#Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
import pandas as pd

In [84]:
#Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
#[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
authors = pd.DataFrame({'author_id':[1, 2, 3], 
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id','author_name'])


In [85]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [86]:
#Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
#[1, 1, 1, 2, 2, 3, 3],
#['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
#[450, 300, 350, 500, 450, 370, 290].
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]}, columns=['author_id','book_title','price'])

In [87]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

# Задание 2

In [88]:
#Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.
authors_price = pd.merge(authors, book, on = 'author_id', how = 'outer')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

# Задание 3

In [89]:
#Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.
authors_price.nlargest(5, 'price')

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

# Задание 4

In [93]:
#Создайте датафрейм authors_stat на основе информации из authors_price.
#В датафрейме authors_stat должны быть четыре столбца:
#author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно 
#имя автора, минимальная, максимальная и средняя цена на книги этого автора.

price_agg = authors_price.groupby('author_name')['price'].agg([np.min, np.max, np.mean])
price_agg.rename(columns={'amin': 'min_price', 'amax': 'max_price', 'mean': 'mean_price'}, inplace=True)
price_agg


min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000

# Задание 5

In [91]:
#Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, 
#какая обложка у данной книги - твердая или мягкая.
#В этот столбец поместите данные из следующего списка:
#['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].

authors_price['cover'] = ['твердая','мягкая','мягкая','твердая','твердая','мягкая','мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [104]:
'''Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.
Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",
а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при 
необходимости загрузите библиотеку Numpy.
'''
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'], columns=['cover'], aggfunc=np.sum)
book_info.fillna(0, inplace = True)
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [107]:
'''Назовите полученный датасет book_info и сохраните его в формат pickle под названием 
"book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, 
что датафреймы book_info и book_info2 идентичны'''
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0