In [1]:
import numpy as np

In [2]:
a = [i for i in range(10)]

In [3]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
b = np.array(a)

In [5]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
b = np.array([i for i in range(10)])

In [9]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
c = (0,1,2,3,4,5,6,7,8,9)

In [11]:
b = np.array(c)

In [12]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
type(b)

numpy.ndarray

In [15]:
b = np.array(a, dtype = float)

In [16]:
a = [0,1,2,3,4,5,6,7,8,9.9]

In [17]:
b = np.array(a, dtype = int)

In [18]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.array(a, dtype = float)

In [21]:
b

array([0. , 1. , 2. , 3. , 4. , 5. , 6. , 7. , 8. , 9.9])

In [22]:
b = np.array(a, dtype = str)

In [23]:
b

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9.9'], dtype='<U3')

In [24]:
a = ['abc', 1,2,3]

In [25]:
b = np.array(a)

In [26]:
b

array(['abc', '1', '2', '3'], dtype='<U3')

In [28]:
b.dtype

dtype('<U3')

In [29]:
a = [0,1,2,3.125]

In [30]:
b = np.array(a)

In [31]:
b

array([0.   , 1.   , 2.   , 3.125])

In [32]:
b.dtype

dtype('float64')

In [33]:
b[0]

0.0

In [34]:
b[1]

1.0

In [35]:
b[2]

2.0

In [36]:
b[3]

3.125

In [37]:
b.ndim

1

In [38]:
b.shape

(4,)

### 2D array

In [39]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
              [10,11,12,13,14,15,16,17,18,19],
              [20,21,22,23,24,25,26,27,28,29]])

In [40]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [41]:
b.shape

(3, 10)

In [42]:
b.ndim

2

In [43]:
b.size

30

In [44]:
b[0][0]

0

In [45]:
b[1,1]

11

In [46]:
b[0,-1]

9

In [47]:
b[2,5]

25

In [49]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [50]:
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [51]:
b[:2,:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [52]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [53]:
c = b[1:, 5:]

In [54]:
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [55]:
c[1,4] = 999

In [56]:
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [57]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [58]:
b[1,5] = 555

In [59]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [60]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [61]:
c = b[1:,5:].copy()

In [62]:
c

array([[555,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [63]:
c[0,0] = 777

In [64]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 555,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [65]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [66]:
b[1,5] = 888

In [67]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14, 888,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [68]:
c

array([[777,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

### Data types

In [70]:
b = np.array([1., 2., 3.], dtype = np.float32)

In [71]:
b

array([1., 2., 3.], dtype=float32)

In [72]:
b = np.array([1., 2., 3], dtype = np.float64)

In [73]:
b

array([1., 2., 3.])

In [75]:
b.dtype

dtype('float64')

In [76]:
b = np.array([1, 2, 3], dtype = np.int32)

In [77]:
b

array([1, 2, 3])

In [78]:
b.dtype

dtype('int32')

In [80]:
b = np.array([1, 2, 3], dtype = np.int64)

In [81]:
b

array([1, 2, 3], dtype=int64)

In [82]:
b.dtype

dtype('int64')

### Операции с векторами

In [83]:
a = np.array([0, 1, 2, 3, 4])

In [84]:
b = np.array([5, 6, 7, 8, 9])

In [85]:
a.size

5

In [86]:
b.size

5

In [87]:
a.shape

(5,)

In [88]:
b.shape

(5,)

### Сложение веккторов

In [90]:
c = a + b

In [91]:
c

array([ 5,  7,  9, 11, 13])

In [94]:
x1 = [0, 1, 2, 3, 4]
x2 = [5, 6, 7, 8, 9]

In [95]:
x1 + x2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [97]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

### Вычитание векторов

In [98]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

In [100]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

In [102]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

In [103]:
a.shape == b.shape

True

### Умножение вектора на скаляр

In [104]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [106]:
c = a * 2
c

array([10,  8, 16,  8,  6])

In [107]:
c = -10 * a
c

array([-50, -40, -80, -40, -30])

In [108]:
c = 0.5 * a

In [109]:
c

array([2.5, 2. , 4. , 2. , 1.5])

In [110]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [111]:
a = np.array([5, 4, 8, 4, 3])
a

array([5, 4, 8, 4, 3])

In [112]:
# Вариант 1
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [113]:
# Вариант 2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [114]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

In [115]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [116]:
a.shape

(3,)

In [117]:
b.shape

(3,)

In [119]:
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

In [120]:
a @ b

32

In [122]:
sp = np.dot(a, b)
sp

32

### Операции с матрицами

In [131]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [132]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [133]:
A.shape

(3, 2)

In [134]:
B.shape

(3, 2)

#### Сложение матриц

In [135]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [136]:
C = np.add(A, B)

In [137]:
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Вычитание матриц 

In [138]:
A = np.array([[11, 13],
              [16, 9],
              [8, 15]])

In [139]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [140]:
D = A - B

In [141]:
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

In [143]:
D = np.subtract(A, B)
D

array([[ 5,  6],
       [ 8,  0],
       [-2,  4]])

#### Умножение матрицы на скаляр

In [145]:
X = np.array([[1, 2],[3, 4]])
X

array([[1, 2],
       [3, 4]])

In [147]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

In [150]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])

#### Умножение матриц

In [158]:
X1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [159]:
X2 = np.array([[7, 8, 9, 10],
               [11, 12, 13, 14]])

In [160]:
X1.shape[1] == X2.shape[0]

True

In [161]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [163]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [164]:
Z.shape

(3, 4)

In [165]:
Z[0, 0]

29

#### Модуль numpy.linalg: возведение матрицы в квадрат 

In [166]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [167]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [169]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

#### Создание единичной матрицы

In [170]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Умножение матрицы на единичную матрицу

In [182]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [183]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [185]:
np.dot(A,I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [186]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [187]:
np.dot(I,A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### Транспонирование матрицы

In [188]:
A = np.array([[11, 13],
              [16, 9],
              [8, 15]])

In [191]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

In [193]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

In [194]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [196]:
Y = np.array([[0, 1],
              [3, 4],
              [6, 7],
              [2, 5]])

In [197]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [198]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

#### Вычисление определителя и ранга матрицы 

In [199]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [200]:
np.linalg.det(A)

0.0

In [201]:
np.linalg.matrix_rank(A)

2

In [202]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [203]:
np.linalg.det(B)

85.99999999999997

In [204]:
np.linalg.matrix_rank(B)

3

#### Вычисление обратной матрицы

In [205]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [206]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [208]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

#### Автоматическое создание массивов

In [210]:
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [212]:
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [213]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [216]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [217]:
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

In [218]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [219]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [220]:
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

#### Генерация случайных чисел 

##### numpy.random.sample - случайные числа с равномерным распределением в промежутке [0.0, 1.0)

In [221]:
np.random.sample()

0.8758884697205069

In [222]:
np.random.sample(3)

array([0.54392972, 0.14144531, 0.11432337])

In [223]:
np.random.sample((2, 3))

array([[0.23485444, 0.82792383, 0.69665838],
       [0.76396816, 0.09836226, 0.58823517]])

In [224]:
np.random.sample((48, 64, 3))

array([[[8.24305863e-01, 2.79125165e-01, 4.45101895e-01],
        [8.92771101e-03, 5.98430394e-01, 4.98971257e-01],
        [8.42319473e-01, 2.37372536e-01, 6.88239111e-01],
        ...,
        [7.85022203e-01, 9.46236612e-01, 6.65411818e-01],
        [8.82853048e-01, 1.59145025e-01, 6.07061385e-01],
        [8.02135267e-01, 6.83160555e-01, 5.17065269e-01]],

       [[7.59743567e-01, 1.13364003e-01, 4.11674520e-01],
        [2.13983864e-02, 8.36022430e-01, 9.05731526e-01],
        [7.57519570e-01, 2.54887106e-01, 7.36960055e-01],
        ...,
        [7.53503861e-01, 3.05525252e-01, 1.28100556e-02],
        [6.17081346e-01, 1.03761083e-01, 7.88986128e-01],
        [1.47870479e-01, 7.86450161e-01, 1.99964637e-01]],

       [[2.58037811e-01, 2.97986410e-02, 4.96179953e-01],
        [4.85489015e-01, 9.43196607e-01, 5.41074843e-01],
        [5.72693391e-01, 2.66098139e-01, 3.89410830e-01],
        ...,
        [4.17191300e-01, 6.08502151e-01, 2.75248100e-01],
        [7.48154901e-01, 5.02

#### numpy.random.randn - случайные числа с нормальным распределением (среднее значение = 0, СКО = 1)

In [225]:
np.random.randn(10)

array([-0.83675143, -0.16451808, -0.53948632,  1.73974496, -0.05845687,
        1.67194227, -0.66845273, -0.21803119,  0.98625526,  0.46044422])

In [226]:
np.random.randn(3, 4)

array([[ 0.61391669, -0.52361093,  0.17136265, -0.88014756],
       [-0.23387212, -1.84934298, -0.87133805,  1.11594754],
       [ 0.03018199, -1.099474  , -0.91670524, -0.9200877 ]])

##### numpy.random.randint - массив из целых чисел

In [227]:
np.random.randint(0, 100, 10)

array([69, 56, 47, 29, 22, 27, 20,  9, 40, 48])

In [228]:
np.random.randint(0, 10, (3, 4))

array([[7, 7, 2, 4],
       [2, 0, 6, 8],
       [2, 7, 1, 6]])

In [229]:
#numpy.random.choice - случайный выбор элементов из массива
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [232]:
np.random.choice(b)

3

In [233]:
np.random.choice(b, 3)

array([2, 5, 4])

In [234]:
np.random.seed(42)

In [235]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

#### Изменение формы массива

In [237]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [238]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [239]:
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [240]:
np.reshape(a, (-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [241]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [243]:
a.resize(3, 4)

In [244]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [245]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

#### Соединение массивов 

In [246]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [247]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [249]:
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [250]:
a.shape, b.shape, v.shape

((2, 3), (2, 3), (4, 3))

In [252]:
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [254]:
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [255]:
a.shape, b.shape, h.shape

((2, 3), (2, 3), (2, 6))

In [256]:
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [258]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

#### Выбор данных

In [260]:
a = np.random.randint(0, 20, 10)
a

array([ 1,  0, 11, 11, 16,  9, 15, 14, 14, 18])

In [261]:
a[a > 10]

array([11, 11, 16, 15, 14, 14, 18])

In [262]:
a[(a > 10) & (a % 2 == 0)]

array([16, 14, 14, 18])

In [263]:
a[(a > 10) | (a % 3 == 0)]

array([ 0, 11, 11, 16,  9, 15, 14, 14, 18])

#### numpy.where - первый вариант применения 

In [264]:
# Возвращает индексы чисел, удовлетворяющих условию
np.where(a > 10)

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [265]:
a[np.where(a > 10)]

array([11, 11, 16, 15, 14, 14, 18])

#### numpy.where - второй вариант применения 

In [266]:
a = [1, 4, 7]
b = [9, 2, 5]

In [267]:
# Если в условии True, то берем элементы из массива a
# если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

#### Сортировка

In [268]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

In [272]:
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [273]:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [274]:
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [275]:
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

#### Случайное перемешиание массивов 

In [276]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [277]:
np.random.shuffle(a)

In [278]:
a

array([1, 9, 8, 5, 4, 2, 0, 7, 3, 6])

In [279]:
a = np.arange(12).reshape(4, 3)

In [280]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [281]:
np.random.shuffle(a)

In [282]:
a

array([[ 9, 10, 11],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  1,  2]])

#### Метематические действия с массивами 

In [283]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [284]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [285]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [286]:
a.sum()

21

In [287]:
a.sum(axis = 0)

array([5, 7, 9])

In [288]:
a.sum(axis = 1)

array([ 6, 15])

In [289]:
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

In [291]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [293]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [294]:
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

#### Broadcasting

In [295]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

In [296]:
b = np.array([1, 2])

In [297]:
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

In [298]:
c = np.array([[1],
              [2],
              [3]])

In [299]:
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

#### Статистические функции 

In [300]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 3,  8, 11,  1],
       [ 9,  8,  9,  4],
       [ 1,  3, 11, 11]])

In [301]:
a.min()

1

In [302]:
a.min(axis = 0)

array([1, 3, 9, 1])

In [303]:
a.max(axis = 1)

array([11,  9, 11])

In [304]:
a.mean(axis = 0)

array([ 4.33333333,  6.33333333, 10.33333333,  5.33333333])

In [305]:
a.std(axis = 0)

array([3.39934634, 2.3570226 , 0.94280904, 4.18993503])

#### Запись и чтение массива из файла 

In [306]:
np.save('a.npy', a)

In [307]:
b = np.load('a.npy')

In [308]:
b

array([[ 3,  8, 11,  1],
       [ 9,  8,  9,  4],
       [ 1,  3, 11, 11]])